### PR TITLE
Implement StopAfterThresholdReached hook

### PR DESCRIPTION
**Pull request by iver56**
This hook stops the training when a certain accuracy, for example 97 %, is reached. Since it might be useful for others, I thought I'd share it.

Example usage:

```python
trainer.add_hook(bs.hooks.StopAfterThresholdReached('validation.Accuracy',
                                                    threshold=0.97,
                                                    criterion='at_least'))
```

This needs a test and some documentation. If there would be documentation and tests for the existing `EarlyStopper`, then I could write similar docs and tests for this hook.

### CODE REVIEW

**Comment by flukeskywalker** [comment]
Thanks! Here are my thoughts:

1. The behavior for 'min' and 'max' criteria is contrary to `EarlyStopper`, and I believe incorrect.
2. 'at_least' and 'at_most' seem confusing (the second one more so). It's probably best to simply use 'min' and 'max', which should be easier to explain in the docs: *The hook stops training if the minimum/maximum value reaches the threshold*. 
2. `threshold` should not have a default value.
3. Can you please add some doc and example usages? :)

**Comment by iver56** [comment]
I can fix those things. Re "at_least": My thinking went something like "stop when accuracy is _at least_ 97 %".

When it comes to documentation, I think I'll wait until there's documentation with examples for `EarlyStopper`. Then I can copy, paste and adapt so the documentation style becomes consistent.

**Comment by flukeskywalker** [comment]
Yes, 'at least' parses fine, but saying *stop when loss is at most 0.1* doesn't really work well.

**Comment by iver56** [comment]
@flukeskywalker I've fixed the things you mentioned

**Comment by flukeskywalker** [comment]
Thanks!

**Pull request merged**
