### PR TITLE
Update installation instructions

### PR DESCRIPTION
**Pull request by iver56**
I tried to install brainstorm on a fresh Ubuntu-instance, and some steps failed. I've updated the installation steps according to what worked for me.

### CODE REVIEW

**Comment by Kaixhin** [comment]
Concurs with [what I have](https://github.com/Kaixhin/dockerfiles/blob/master/brainstorm/Dockerfile). May also need `six` upgraded, but that doesn't need to be documented.

**Comment by iver56** [comment]
Yeah, I noticed problems with the version of `six` as well, but didn't write that down

**Comment by flukeskywalker** [comment]
Thanks! I would not recommend installing the python packages system-wide with `sudo` though. It's better to install in a [virtualenv](https://virtualenv.readthedocs.org/en/latest/), which many people already use, and keeps things clean.

**Comment by iver56** [comment]
Good point. I usually use virtualenv, but this time I just wanted to try brainstorm on a temporary virtual machine running Ubuntu, so I didn't worry about keeping things clean. It's a valid use case, though, so people might benefit from having a tutorial for it. At least I know I would like that, because I just spent two days trying to get Brainstorm and all its dependencies to interoperate properly in order to run it on the GPU, with the help of CUDA.

Btw, I just found that Caffe has a good tutorial:
https://github.com/BVLC/caffe/wiki/Install-Caffe-on-EC2-from-scratch-%28Ubuntu,-CUDA-7,-cuDNN%29

**Comment by flukeskywalker** [comment]
I agree. We do need a detailed tutorial in the documentation. There is some work on this in the `docs` branch, and we'll improve it further.

Can you tell us more about what led to difficulties in installation? We don't want it to take 2 days for anyone.

**Comment by iver56** [comment]
* All attempts at trying to get CUDA 7.5 to work failed. Then I tried to install 7.0 using a the package manager method, but it ended up installing 7.5 anyway. I had to use the runfile method to install CUDA 7.0. I had problems with linux headers while trying to install CUDA 7.0 using the runfile. I had to delete and regenerate my `/boot/grub/menu.lst`. Also, I had to move my runfile to a different partition to get enough space for the CUDA installation, which seemingly requires about 4,5 GB of free space. Finally, nvidia's cuda installation instructions didn't make it clear where I should put the PATH variable for CUDA. Should it be in `/etc/environment` or `~/.bashrc`? Or perhaps in `.profile`?

* I had trouble with `six`. I had to upgrade it, but then I ended up having two installations, where the old version was owned by the OS, and pip would not remove it. That was a problem. I ended up removing it by hand, and that seemed to work.

* I had to manually patch `__init__.py` in pytools. See https://bitbucket.org/gutworth/six/issues/107/import-intern-module-from-sixmoves

* And then there were minor issues where I, for example, had to throw in an extra `sudo apt-get update` and prepend `sudo` to some commands, as indicated by the changes in this pull request

**Comment by Kaixhin** [comment]
FYI I've made [CPU-only](https://hub.docker.com/r/kaixhin/brainstorm/) and [CUDA](https://hub.docker.com/r/kaixhin/cuda-brainstorm/) Docker images to have preinstalled distributions of Brainstorm available for download. You can either copy the format from the [Lasagne docs](https://lasagne.readthedocs.org/en/latest/user/installation.html#docker-images) or ask me to do it once the `docs` branch is merged.

**Comment by iver56** [comment]
Perfect! I would have used that if I knew about it :)

**Comment by flukeskywalker** [comment]
Thanks guys! 

I'll merge this for now, and point to @Kaixhin's scripts in the docs soon.

Unfortunately, CUDA installation can (still!) be cumbersome but we can't really do much about that.

**Pull request merged**
