### PR TITLE
RMSprop, AdaDelta and Adam steppers

### PR DESCRIPTION
**Pull request by kashif**
For issue #46

### CODE REVIEW

**Comment by flukeskywalker** [comment]
Thanks, looks good! Have you tried training with it yet?

**Comment by kashif** [comment]
not yet, let me add some tests and the rest of the steppers etc and then will try it with examples... 

should i rename the issue with [WIP] ?

**Comment by flukeskywalker** [comment]
Cool. There aren't many issues yet, so it's also fine not to label.

**Comment by kashif** [comment]
@flukeskywalker should be ready to merge.

**Comment by flukeskywalker** [comment]
@kashif Back from vacations now, will review and merge soon. HNY!

**Comment by kashif** [comment]
no worries @flukeskywalker HNY to you too! :tada:

**Pull request closed without merging**
