### PR TITLE
we can pip install from source, no need to clone

### PR DESCRIPTION
**Pull request by tovmeod**

### CODE REVIEW

**Comment by flukeskywalker** [comment]
This is fine, but it looks like you left the cloning command in there, as well as making local docs (for which one needs to clone).
You're right though -- we'll soon move detailed installation instructions to documentation, and only keep direct installation instructions in the README.

**Comment by tovmeod** [comment]
Actually I just realized that brainstorm is on pypi, one could just pip install brainstorm

**Comment by flukeskywalker** [comment]
While technically true, this is not preferable yet since pip install will fail currently if Numpy is not already installed.
Don't worry though, we are working on fixing these issues and streamlining installation in the docs branch!

**Comment by tovmeod** [comment]
I see, setup.py imports numpy, of course it will fail.
But why is numpy imported on setup.py, also it decides if cython is going to be used based on if it can import it.

**Comment by flukeskywalker** [comment]
It's needed because the Cython extension needs to include files from Numpy. The workaround is already in the docs branch (which we'll merge this week), so no need to worry :) You can safely close this issue.

**Comment by tovmeod** [comment]
There goes my dream of having my name on a big project. :)

**Pull request closed without merging**
